### ISSUE TITLE
pyez-config does not update "changed" field even when configuration is changed

### ISSUE THREAD

**Issue by nsw3550** [DataKnox/nornir_pyez#18]
py-ez config reports changed:False even when it does commit a config change:

`result = targets.run(`
`    name="Change hostname",`
`     task=pyez_config, `
`    payload="set system host-name SRX-DR02",`
`    data_format="set",`
`    commit_now=True`
`    ) `
`    print_result(result)`

`* SRX-DR01 ** changed : False **************************************************`
`vvvv Change hostname ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv INFO`
`Successfully deployed config`
 `set system host-name SRX-DR02`
`^^^^ END Change hostname ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`

**Comment by geg347** [comment]
Hello,
A bit late but I tried to set that changed field at True when calling for a Result object.
But I think we can skip this because it should be returned by Nornir when you have real changes on a device.

Another thing is that with the concept of candidate configuration and commits with Juniper, I don't know when to trigger this flag (when configuring or when committing afterward?) (Here you put the flag commit_now so this changed flag could have been set to True).

I also tried to remove this in the output but it requires changes on Nornir_utils print_result function so not in our scope here and this flag may be useful with any other vendor.
So I propose to close this issue as even if this changed flag is always false it doesn't impact the behaviour of the code.
